name: PR Checks

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Checks if the PR is in draft status and fails if so, which does 2 things:
  #  - Prevents the PR from being merged in that state
  #  - Prevents all downstream jobs from running
  # Additionally, require each test to pass before running the next to prevent
  # running unnecessary jobs if any upstream jobs already failed
  draft:
    name: 'Check Draft Status'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fail draft PRs'
        if: github.event.pull_request.draft == true
        run: |
          echo "Skipping execution for draft PR"
          exit 1

  check-version-label:
    name: 'Check Version Label'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fail if not exactly one version label'
        id: check
        run: |
            LABELS="${{ join(github.event.pull_request.labels.*.name, ' ') }}"
            VERSION_LABELS=$(echo $LABELS | tr ' ' '\n' | grep -E '^version:(patch|minor|major)$' || true)
            LABELS_COUNT=$(echo "$VERSION_LABELS" | wc -w)
            if [[ "$LABELS_COUNT" -ne 1 ]]; then
                echo "Exactly one version label is required. Exiting."
                exit 1
            fi
        shell: bash
